title: go-Hoyolab
repo: dvgamerr-app/go-hoyolab
version: v1.0
author:
  username: dvgamerr
  name: Kananek T.
  website: https://dvgamerr.app/

description: >
  Hoyolab Automatic Daily Check-in Hoyoverse Game.
  You only need to run it once, then it will continue

# Build settings
cronitor_token: a08df15d735c0c7518246129767fd319

baseurl: /go-hoyolab
remote_theme: dvgamerr-app/minima-lite

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  date_format: "%-d %b %Y"
  social_links:
    - { platform: devto,          user_url: "https://dev.to/dvgamerr" }
    - { platform: facebook,       user_url: "https://www.facebook.com/dvgamerr" }
    - { platform: x,        user_url: "https://x.com/dvgamerr" }
    - { platform: youtube,        user_url: "https://www.youtube.com/channel/UCbMNge3pQHkb3avJvUj4hLA" }
youtube_username: 

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
# header_pages:
#   - about.md
